# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%math_database_driver%"
        host:     "%math_database_host%"
        port:     "%math_database_port%"
        dbname:   "%math_database_name%"
        user:     "%math_database_user%"
        password: "%math_database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true